/**
 * buildInfo.js — AUTO-GENERATED by scripts/gen-build-info.js. Do not edit.
 * Regenerated on every bundle/build so the Settings version reflects each push.
 */
export default {
  version: '1.1.0',
  build: 9,
  commit: 'f9aea3f',
  builtAt: '2026-06-20',
};
